name: Despertador de V-Panel

on:
  schedule:
    # Lo bajamos a 10 minutos para compensar los retrasos de GitHub
    - cron: '*/10 * * * *'  
  workflow_dispatch:        

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Enviando señal a Render
        run: |
          curl -s -I https://catalogo-vpanel.onrender.com
          echo "Señal enviada con éxito"
